name: Build examples
on:
  push:
    branches:
    - master
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build-examples:
    name: Build for ${{ matrix.idf_target }} on ${{ matrix.idf_ver }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        idf_ver: ["release-v5.2"]
        idf_target: ["esp32", "esp32s2", "esp32c3", "esp32s3", "esp32c2", "esp32c6", "esp32h2"]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Build example
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ matrix.idf_ver }}
        target: ${{ matrix.idf_target }}
        path: examples/i2c_agmt